name: Deploy Angular App

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Angular project
        run: npm run build -- --configuration production --base-href "https://ashishskg.github.io/freshmart/"

      - name: Deploy to GitHub Pages
        run: |
          npm install -g angular-cli-ghpages
          ngh --dir=dist/freshmart
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
